# Generated by Django 3.2.8 on 2021-10-11 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20211009_1401'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.AddField(
            model_name='room',
            name='white_board',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
