# Generated by Django 3.2.8 on 2021-10-11 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20211011_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='Whiteboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wid', models.UUIDField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='room',
            name='white_board',
        ),
        migrations.AddField(
            model_name='room',
            name='wb_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.whiteboard'),
        ),
    ]
